import { UserProvider } from "@/context/authContext";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { ChatContextProvider } from "@/context/chatContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Messenger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <ChatContextProvider>
          <body className={inter.className}>{children}</body>
        </ChatContextProvider>
      </UserProvider>
    </html>
  );
}
